### ISSUE TITLE
Translate the JS Rising Stars in Chinese ?

### ISSUE THREAD

**Issue by michaelrambeau** [michaelrambeau/risingstars2016#10]
Hello @egoist,

Just in case, would you like to translate the "2016 JavaScript Rising Stars" mini site in Chinese ? 🇨🇳 .
Or do you know someone who could do the translation ?

I created a multilingual version of the site, using [Gatsby](https://github.com/gatsbyjs/gatsby) in this branch: https://github.com/michaelrambeau/risingstars2016/tree/feature/multilingual

It's only about markdown and yml files to translate (see #9 issue for details)

Of course I will add your name on the page if you work on the project 😄 .

Thank you in advance!

**Comment by wangshijun** [comment]
@michaelrambeau I have finished the translation work, see PR #14 for detail, thanks

**Comment by michaelrambeau** [comment]
Thank you very much @wangshijun 

The Chinese version is live!

https://risingstars2016.js.org/zh/

![image](https://cloud.githubusercontent.com/assets/5546996/23827951/a99a0f68-0704-11e7-8be2-721c9bb2afb9.png)
