### ISSUE TITLE
Hapi link is broken

### ISSUE THREAD

**Issue by sapegin** [michaelrambeau/risingstars2016#4]
In `projects.json`:

```
url: "hapijs.com",
```

This files looks autogenerated, so I’m not sending a PR for that.

P. S. Same for `brunch.io`.

**Comment by michaelrambeau** [comment]
It's corrected too, I manually added the missing `https`.
Thank you!

**Comment by sapegin** [comment]
Awesome! There’s also `brunch.io`.

**Comment by michaelrambeau** [comment]
For me `brunch.io` is not broken, I think it's just that it's the only link that starts with `http` instead of `https`, in this case Chrome does not display the http protocol when you "mouse hover" the link.

**Comment by sapegin** [comment]
Yeah, Brunch is fine. I was probably looking somewhere else ;-£
