### ISSUE TITLE
Phenomic stars count is weird

### ISSUE THREAD

**Issue by MoOx** [michaelrambeau/risingstars2016#8]
Hi,

Thanks for this "tool", pretty nice to follow trends.
I am the author of Phenomic (static website generator using React) and I see +5xx stars but it's more +1.x stars in 2016 (see it by yourself http://www.timqian.com/star-history/#MoOx/phenomic)

Just curious where the data you have comes from.

**Comment by michaelrambeau** [comment]
Hello @MoOx ,
I have fixed the numbers.
I am sorry for the mistake, actually the calculation about the number of star was wrong for some projects that were not under my radar at the beginning of 2016, it's my bad.

Bravo pour ton projet, à propos, et bonne continuation à Toulouse où je vivais avant de partir à Osaka 😉  !

**Comment by MoOx** [comment]
Merci :)
